### ISSUE TITLE
Additional initiative card functionalities

### ISSUE THREAD

**Issue by tinwe** [Stefouch/t2k4e#100]
### Is your feature request related to a problem? Please describe.
Would it be possible to upgrade the current initiative macros for T2k, with a macro that draws initiative for participant in the battle at once. The current macro becomes rather cumbersome since you can only click one player at a time, while you also have to confirm the amount of initiative cards for each draw. So if you even run into large encounters of 10+ participants, each battle round takes several minutes just to draw the initiative cards, which made us use the built in system in Foundry instead.
Bonus 2: It would also have been nice if it supported the RAW option to let all NPC:s share the same initiative automatically.
Bonus 3: If possible, it would also be nice to have an option to hide the iniative of NPC:s to the players, so that they didn't know when the enemies were going to act. That would make it way more exciting and would force them to make much harder strategic decisions with less meta gaming. 

### Who would use it?
Everyone using the initiative card functionality as in the rulebook.

### What part of the system?
Initiative cards

### How would it work?
1. One new macro that quickly populates each contestant in the current battle with new initiative cards, without any popup options.
2. A new setting to bundle all NPC:s together with the same iniatiative card number.
3. A new setting to hide the iniative of NPC:s to the players, so that they didn't know when the enemies were going to act. That would make it way more exciting and would force them to make much harder strategic decisions with less meta gaming. 

### Why should this be added?
To make the drawing of iniative cards much quicker and less of a hazzle. And to support the RAW option to bundle alla NPC iniatives together at the same level. As well as give an option to hide the NPC iniaitive to make it more exciting and force the players to make much more interesting strategic decisions with less meta gaming.

**Comment by Stefouch** [comment]
Might be related to #77

**Comment by Stefouch** [comment]
We (the free league community of developers) are writing a Year Zero Combat module that can handle init cards.

Therefore, this feature request should be solved with this upcoming module.

I'm closing this for now
