### ISSUE TITLE
Weapon "Unarmed" can not be clicked

### ISSUE THREAD

**Issue by doct** [Stefouch/t2k4e#14]
### Describe the Bug
The gear tab of a PC has a Weapons section. The first entry is always "Unarmed". This should be clickable for a Close Combat attack. However, it is not possible to click on Unarmed, hence it is not possible to attack unarmed, making this entry somewhat pointless.

### Severity
- Medium (minor functional impact)

### To Reproduce

1. Create a pc.
2. Open new pc.
3. Switch to GEAR tab.
4. Click on Unarmed. 
5. Nothing happens.

### Expected Behavior
After 4., an attack should be posted to the chat, with an attack button to initiate dice rolling for an Unarmed attack.

(awesome module, btw., thanks! :-) )

**Comment by Stefouch** [comment]
I think I'm gonna just delete the "unarmed" line in the inventory and instead the user can create an "unarmed" weapon and add it to its sheet.

**Comment by doct** [comment]
I think, that's fine. The code is cleaner and the gear entry more flexible and easier to maintain and adapt. It was my workaround anyway :-) Thanks for your efforts!
