### ISSUE TITLE
Weapon "Unarmed" has wrong values

### ISSUE THREAD

**Issue by doct** [Stefouch/t2k4e#15]
### Describe the Bug
The gear tab of a PC has a Weapons section. The first entry is always "Unarmed". The CRIT value is shown as "3". However, according to the Player's Manual, pg. 93, the CRIT value should be "4".

(Your description here.)

### Severity
- Medium (minor functional impact)

### Context
On a PC sheet, in the GEAR tab.

### To Reproduce

1. Go to Context
2. Look at it :-)

### Expected Behavior
CRIT value should be 4.

**Comment by Stefouch** [comment]
Oh! I missed this change from the alpha version. It'll be fixed in the next update
