### ISSUE TITLE
Rolltables broken if formula is equal to base die type

### ISSUE THREAD

**Issue by doct** [Stefouch/t2k4e#17]
### Describe the Bug
When the roll table formula of a roll table is equal to one of the base die, i.e. 1d6, 1d8, 1d10, or 1d12, only a single - or two, for 1d10 or 1d12 - results are ever drawn. For roll tables with no replacement, rolling on the table ends after one (or two) rolls.

If the formula does not match a base die, the table works fine.

Other game systems don't have this issue.

### Severity
- High (a broken feature, major functional impact)

This bug breaks initiative table (10 entries!) and initiative macros, hence combat.

### Context
Any roll table with a formula of 1d6, 1d8, 1d10, or 1d12.

This happens even if ALL modules are deactivated.

### To Reproduce
1. Create a new roll table, with 10 entries, equally weighted, uncheck "Draw with replacement", rebalance table, roll table formula is now 1d10, update table, reset table.
2. Roll on table, result is 1 or 2.
3. Roll on table again, result is 2 or 1.
4. Roll on table again, Warning notification "No results can possibly drawn from this table and formula." appears, no result is returned.
5. Delete last table entry (10), so that there are nine results, re-balance table, roll table formula is now 1d9, update, reset, roll a few times, all works well until all results are drawn.
6. Delete last table entry again (9), so that there are eight results, re-balance table, roll table formula is now 1d8, update, reset table.
7. Roll on table, result is 1.
8. Roll on table again, Warning notification "No results can possibly drawn from this table and formula." appears, no result is returned.

etc.

### Expected Behavior
Random results of table, exhausting all possible results, for every roll table formula.

**Comment by Stefouch** [comment]
Thank you to have spotted this one. This is serious issue linked to the fact that the Twilight 2000 custom dice are replacing the default standard d6, d8, d10 & d12.

I will try to address the problem as soon as possible.
