### ISSUE TITLE
Colum header "COVER" should read "COVERS" for gear armor items

### ISSUE THREAD

**Issue by doct** [Stefouch/t2k4e#19]
### Describe the Bug
This is really very linguistic pedantic nitpicking: on a PC character sheet, on the gear tab, in the armor section, there is a column heading describing, which body part an armor item protects (which is actually a great feature of your implementation!). 

However, the armor item does not give "cover" to a body location, as the header seems to imply, it gives armor. The meaning of COVER is found in the PM pg. 58, and is not related to armor.

What would seem to be correct would be if the header read "covers", because the armor item cover_s_ the body part indicated, though it does not give COVER according to the rules.

### Severity
- Trivial (typos, etc)

### Context
PC character sheet, on the gear tab, in the armor section, there is a column heading "COVER".

(also, important context: sorry, I am German ;-)

### To Reproduce
Look!

### Expected Behavior
"COVER" should read "COVERS"

**Comment by Stefouch** [comment]
Ah, I see your point. I'll make the change.

Thank you for taking the time to write well-documented feature requests and bug issues !

**Comment by doct** [comment]
Happy to bring this great module forward even more! Thanks for your amazing efforts and friendly replies!
