### ISSUE TITLE
Provide a "military unit" character sheet type

### ISSUE THREAD

**Issue by doct** [Stefouch/t2k4e#20]
### Is your feature request related to a problem? Please describe.
No problem, just a helpful feature...

The travel map can be used to put tokens on the map representing military units. Players can then move unit tokens around, to display and discuss the military situation, react to it, and probably change it.

It would be nice, if that token were related to appropriate character sheets, like "military unit" or similar. That character sheet wouldn't need many attributes, percentile health and a description would be a good start. The most important part of that "character" would be its name (i.e., unit designation), and token on the map.

An additional feature could be to somehow represent the unit relationships within the character sheet, so that it were trivial to walk through each side's OOB tree, i.e. regiment a belongs to brigade b, which belongs to division c, etc. But this could also be solved by linking entities in the description field, and putting entities in appropriate subfolders.

### Who would use it?
Grognards. Everyone who wants to represent and dynamically change the military situation on the battlefield.

### What part of the bot?
Character sheet type.

### How would it work?
Upon creating a character, one would select "military unit" as character type. GM can give permission to players to update the unit, and move it's token on the map.

Subordinate units could be listed on a tab, as could a reference to the unit this char is belonging to. The entries would be references to other char entities representing those units.

### Why should this be added?
Because T2K4E is part roleplaying game, but also part military simulation, aka conflict simulation game (cosim). There is already a VASSAL module!

**Comment by Stefouch** [comment]
This is great idea that I love, but it will require a huge load of work (new entity type 'military', new sheet, CSS update, etc.).

I will look into it after the release of the Travel/Party Sheet.

**Comment by doct** [comment]
Sure, no sweat! :-)

Workaround in the meantime is to just use a PC char sheet and ignore all the PC stuff. Or maybe use a journal entry and assign a particular unit icon to the entry, then put a note to the journal entry on the map.

**Comment by Stefouch** [comment]
Actually, it would be easier for me if this kind of "Military Unit" Actor is already available while I'm finishing writing the Coreset Premium modules.

So the next release of the game system will have Military Units.<br/>
And the modules will include the predefined divisions from the Referee's Manual.

**Comment by doct** [comment]
Fantastic!
