### ISSUE TITLE
Weapon Quantity shows in the magazine drop down for a gun

### ISSUE THREAD

**Issue by marroon69** [Stefouch/t2k4e#23]
### Describe the Bug
So when using a weapon you have to select the Magazine, the drop list the weapon plus other magazines you have in your inventory. So in my case I made a AKM with a magazine size of 30 and type of 7.62x39. In the drop down there were two choices

AKM (1)
7.62x39 (30) (2)

The ALM (1) seems to be tied to the the Quantity box on the top of the sheet. Seems like that is not amom but the number of AKMs I have
### Severity
- Medium (minor functional impact)

### Context
This only applies to weapons, grenades use the quantity effectively

### To Reproduce
Create the a weapon and add multiple quantities

### Expected Behavior
The quantity of ALMs should not appear in the magazine list

### Screenshots
![ammo issue](https://user-images.githubusercontent.com/35424343/126188848-67cb9ae2-677c-4aa0-8f94-ca71447c4177.jpg)

### Additional Context
Looking at the quantity for things like grenades' I think it handles it correctly, removing 1 when the item is used but it makes little sense for guns.

**Comment by Stefouch** [comment]
Hi @marroon69,

Thank you for your contribution to the system by reporting bugs you find.

For this particular issue, this is not a bug but a feature. Some weapons might use themselves as ammo, like the M72A3 LAW rocket launcher and the M136 AT4 anti-tank weapon.

Thus, the magazine choice always shows at least the weapon itself.
