### ISSUE TITLE
Can we set the Icon size to .4 at a system level

### ISSUE THREAD

**Issue by marroon69** [Stefouch/t2k4e#24]
### Is your feature request related to a problem? Please describe.
It would be great it the default icon size in the system would be something like 0.4 and not one. Since hexes are 10 meters and multiple people can be in a hex,
### Who would use it?
I would assume everyone would do this on every token on the map

### What part of the system?
Default icon size. 

### How would it work?
Just default the size of the icons

![image](https://user-images.githubusercontent.com/35424343/126194913-5673fb91-3c41-410e-97f3-088a08a6f44d.png)

### Why should this be added?
here is how it looks
![image](https://user-images.githubusercontent.com/35424343/126194707-d1319802-b85e-4563-a16c-deab88062af8.png)

**Comment by Stefouch** [comment]
Indeed, I should maybe consider that.

**Comment by Stefouch** [comment]
I will add a settings in the system's options where you can set a default option for this.

**Comment by marroon69** [comment]
So we may want to think about this....it appears if the icon does not take up the entire you lose the hit "space to move" after making the change....hmmmm
