### ISSUE TITLE
[t2k4e-coreset] Tgb 11 & Tgb 13 images missing on some OS

### ISSUE THREAD

**Issue by Stefouch** [Stefouch/t2k4e#36]
### Describe the Bug

Some users reported an image missing for two vehicles:
- Tgb 11
- Tgb 13

### Severity

- Trivial (typos, etc)

### Context

The files are present, but it seems their names contain characters not supported by some computer.
```
Folder: /modules/t2k4e-coreset/assets/vehicles/
vehicles-swe-terrängbil-11.webp
vehicles-swe-terrängbil-13.webp
```

### Screenshots

![screenshot](https://media.discordapp.net/attachments/877696334579265546/877696362022584400/Screenshot_2021-08-19_at_00.24.11.png)

### Temporary Fix

To temporarily fix this issue, just rename the file by changing the `ä` for a `a` without the `"¨"` dots above it.
Then select the new image for the vehicle Actors.

**Comment by Stefouch** [comment]
This issue will be fixed in the next patch for the `t2k4e-coreset` module.

**Comment by kylania** [comment]
This issue seems to be preventing installation/unzipping of the Core Module in Linux as reported by a user on Discord:
![unknown (1)](https://user-images.githubusercontent.com/119372/142088015-dee271dd-b3a4-4f0f-a0fc-a6398b4543a2.png)

**Comment by Stefouch** [comment]
I will look to push an update asap.
