### ISSUE TITLE
Travel !

### ISSUE THREAD

**Issue by Stefouch** [Stefouch/t2k4e#37]
The Twilight 2000 system is missing a core functionality: support for Travel rules.

I will add a new "Travel" sheet that will allow the GM and the players to track their journey in the travel map.

Something similar as how Journeying is implemented in the Forbidden Lands system.

### To-Do List
- [x] Actor Entity
- [x] Actor Sheet
- [x] Other scripts
- [x] CSS styles
- [x] Tests & Bugfixes

**Comment by lystraeudaimon** [comment]
This is a great idea! 
Would be nice to have something on travel sheet that has the party's total food/water for tracking purposes

**Comment by tinwe** [comment]
How is this feature coming along?
It would be greatly appreciated

**Comment by Stefouch** [comment]
Almost done. And update with the travel sheet should be uploaded soon.
