### ISSUE TITLE
Rotate all the vehicle Tokens so the front faces down

### ISSUE THREAD

**Issue by marroon69** [Stefouch/t2k4e#38]
### Describe the Bug
By default Foundry expects the front of a token to facing down. the main reason for this is the way lighting works. Please rotate all the vehicle icons to have the front of the vehicle facing down.
I posted in several forums within the Discord and this was the answer I receive. 
(Your description here.)

### Severity
- Low (formatting issues, things that don't impact operation)

### Context
Vehicles and lighting

### To Reproduce
Place a UAZ on the map form the compendium
Set Bright Light Radius 20
Set Dim Light Radius 20
set Emission Angle to 90

### Expected Behavior
The light should based on the setup should come from the front of  vehicle token

### Screenshots
![T2k Lights](https://user-images.githubusercontent.com/35424343/130069024-548e004e-512e-4656-854f-710e385544aa.png)
![T2K config](https://user-images.githubusercontent.com/35424343/130069030-879c22a4-edce-4806-b327-ecef1072807d.png)

**Comment by Stefouch** [comment]
See #35 for reference
