### ISSUE TITLE
Replace inline die results buttons with inline die roll request buttons

### ISSUE THREAD

**Issue by kylania** [Stefouch/t2k4e#52]
### Is your feature request related to a problem? Please describe.
By using Item Links and Inline Die Rolls instead of Inline Die Results the quality of life for character creation using Life Paths can be greatly enhanced and more intuitive.

### Who would use it?
Anyone creating a character using Life Paths rules.

### What part of the system?
Dice rolling, Journal Entries, Character Creation.

### How would it work?
Currently the Life Path has all "Roll 1d6 for..." options using the inline die roll of `[[1d6]]`.  This renders on the Journal Entry page as a die icon and the result of a 1d6 roll.  If you click on this icon you simply see that result.  To get it to generate another result you need to close and reopen the Journal Entry.  This makes it impossible to generate values while on the page as a player.

This can be improved by using the Inline Die Roll format, which adds an `/r` command in front of the die roll.  This would be written as `[[/r 1d6]]`.  That will render on the Journal Entry page as a die icon with 1d6 printed next to it and each time the player clicks the button it rolls a six sided die on the Chat Log to generate a new value.  This way people can remain on the Life Path Journal Entry and keep generating new rolls without having to close and reopen.  Additional confusion comes from there not being any obvious dice rolling mechanic, so the player would need to know you could type /roll 1d6 into chat in order to generate a roll.

A further improvement would be to replace all static entries of Specialties on the tables with Item Links to either the imported world Item or even directly from the Compendium.  This way characters can simply drag the result onto their character sheet without having to try to create them from scratch or searching for the Item on a different tab.

For example instead of simply having the word "Runner" in the table for Street Kid Specialties you could link to it by dragging it from the Compendium onto the Journal Entry resulting in a link like this:

`@Compendium[t2k4e-coreset.core-set-items.B5VQErEPVirwjx5U]{Runner}`

That would be clickable to view the Specialty Item and draggable onto the character sheet - a core feature of Foundry VTT's character building process.

In the attached gif you'll see examples of how it is by default and how it works improved as well as examples for a specialty which was linked from the Compendium and draggable onto the sheet.

### Why should this be added?
These are quality of life changes to harness the capabilities of Foundry VTT and make creating a character via Life Path options much smoother and more intuitive for players.  I would suggest that any time a die roll is requested in the rules that it be in the `[[/r 1d6]]` format so that people know it's a die roll and can click it to roll rather than simply be presented with a single result from an unknown die roll.

### Additional context
Attached you'll find a gif showing the process before and after the changes I'm suggesting.

https://user-images.githubusercontent.com/119372/135730097-19734a1e-49d3-4df3-ae5d-db95a7cd4ba6.mp4

Events at timestamps:
0:08 - I show how a "2" result had been generated when opening this page and clicking on it only displays the same "2" result again, no way to generate a new result unless you know you can close and reopen the page.
0:20 - This is an example of a rollable button where clicking it generates a roll and result on the Chat Log, in this case a "3" for Sniper specialty.
0:27 - The user would have to know to then click on Items tab, find Specialties, scroll down to Sniper and drag onto the Character sheet or else they'd have to manually create the specialty from a blank template from the sheet itself.
0:38 - This shows the ability to roll on the same table again, a feature of the Life Path character creation but this time with pre-generated links so that I was able to drag the result from the table I was already looking at onto my character sheet to add the "Melee" specialty.
0:49 - Shows the default inline die result format currently in place.
0:51 - Shows the suggested inline die roll format for allowing repeated use of the button.
0:57 - Shows the link of the Runner specialty pointing at the Core Set compendium, to have a known itemID to link to (you can do this by dragging the Item from the Compendium onto the Journal Entry edit box.
1:03 - Shows the source for that Runner specialty which is what was dragged onto that table to create the link.

**Comment by kylania** [comment]
This wiki page covers many of the formatting options for dice rolls and links and the like:

https://foundryvtt.wiki/en/basics/Chat

**Comment by Stefouch** [comment]
Thanks @kylania for this very complete report. I agree with your analysis and will work to implement these suggestions.
