### ISSUE TITLE
Add additional vehicle options for conversions/expansions/custom

### ISSUE THREAD

**Issue by rsimmerm** [Stefouch/t2k4e#53]
### Is your feature request related to a problem? Please describe.
No, it's more of an addition/enhancement.

### Who would use it?
Game Masters primarily, but players too.

### What part of the system?
Vehicle Types

### How would it work?
Added other vehicles types for : Flying (Chopper/Planes), Water (Boats/Ships) etc.

### Why should this be added?
Only gives Tracked/Wheeled options currently, 

### Additional context
I don't think so.

**Comment by Stefouch** [comment]
A few extra types will be added in the next update.

**Comment by rsimmerm** [comment]
Awesome.
