### ISSUE TITLE
Typo @JournalEntry[Encounters] STRAGGLERS

### ISSUE THREAD

**Issue by mogrogh** [Stefouch/t2k4e#62]
### Describe the Bug
A typo in @JournalEntry[Encounters] STRAGGLERS

### Severity
- Trivial (typos, etc)

### Additional Context
first **hance** to steal 

Missing the c in chance

**Comment by Stefouch** [comment]
Thank you @mogrogh ! I found the typo and It'll be fixed in the next update.
