### ISSUE TITLE
Warning for outdated content in core module in debug.log

### ISSUE THREAD

**Issue by r-valyar** [Stefouch/t2k4e#68]
### Describe the Bug
A warning in the debug.log related to the official core package

`{"level":"warn","message":"Package t2k4e-coreset contains 7 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}`

### Severity
Unknown, since the system is not V9 ready and can't say what the implication is.

### Context

(Your context here.)

### To Reproduce
Open the debug.log

### Expected Behavior
No errors or warnings in the logs.

**Comment by Stefouch** [comment]
Thanks @r-valyar for the issue report. I've found what it's causing this error log and it's very minor. Not a big deal until V10.
