### ISSUE TITLE
Draw encounter card macro not working after 2.0 update

### ISSUE THREAD

**Issue by tinwe** [Stefouch/t2k4e#76]
### Describe the Bug
The Draw Encounter Card macro isn't responding or doing anything after the 2.0.0 and 2.0.1 update for Foundry 0.9

(Your description here.)

### Severity

- High (a broken feature, major functional impact)

### Context

The Draw Encounter Card macro

### To Reproduce
Click or import the Draw Encounter Card macro

### Expected Behavior
Should select and display an Encounter Card

**Comment by Stefouch** [comment]
Do you have any error displayed in the console log? (to show the console log, type F12 and select the "consol" tab during the game)

**Comment by tinwe** [comment]
Uncaught (in promise) TypeError: Cannot read property 'encounter' of undefined
[No packages detected]
    at eval (eval at _executeScript (foundry.js:16878), <anonymous>:4:35)
    at Macro.eval (eval at _executeScript (foundry.js:16878), <anonymous>:5:7)
    at Macro._executeScript (foundry.js:16880)
    at Macro.execute (foundry.js:16837)
    at Hotbar._onClickMacro (foundry.js:52124)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)
eval @ VM400:4
eval @ VM400:5
_executeScript @ foundry.js:16880
execute @ foundry.js:16837
_onClickMacro @ foundry.js:52124
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by tinwe** [comment]
Ah, nvm, forgot to re activate the Twilight 2000 module myself. That is why the Encounter cards stopped working for me. 
Now they also works for 0.9
Embarrasing :S

**Comment by Stefouch** [comment]
No worry!
I'm closing this ticket then;
