### ISSUE TITLE
Sheet Display Broken -- Tabs Distorting View

### ISSUE THREAD

**Issue by rvhguy** [Stefouch/t2k4e#78]
### Describe the Bug

The sheets are showing tabs that are extended, and the main sheet cannot scroll because the tab image is too long.

### Severity

- High (a broken feature, major functional impact)

### Context

This is applying to both me on Safari and people on PC using Chrome, Edge and Firefox.

### To Reproduce

Open a character sheet.

### Expected Behavior

The tabs should look like they are supposed to.

### Screenshots
![Screen Shot 2022-01-27 at 8 33 34 PM](https://user-images.githubusercontent.com/67940748/151487783-0c342925-6e93-4d53-8ff7-3af336542de2.png)
![Screen Shot 2022-01-27 at 8 34 04 PM](https://user-images.githubusercontent.com/67940748/151487839-5ec91dce-f478-4f70-a91a-63a32206a2d7.png)

### Additional Context
It seems to have changed in the last week!

**Comment by Stefouch** [comment]
Did it happen after you updated Foundry to the patch that was released yesterday?

**Comment by rvhguy** [comment]
I did not, but I run on Forge VTT so they may have done so.

**Comment by Stefouch** [comment]
Related to https://gitlab.com/foundrynet/foundryvtt/-/issues/6615
