### ISSUE TITLE
CUF dice modifier not applying correctly.

### ISSUE THREAD

**Issue by AtraAngelis** [Stefouch/t2k4e#80]
### Describe the Bug
Dice Modifier for any CFU roll not applying correctly to dice roll

### Severity
- High (a broken feature, major functional impact)

### Context
When applying a critical injury to a player that affects a die roll with a modifier. The modifier does not apply the die step correctly or at all.

### To Reproduce
1- Generate a critical injury for the player from the provide macros (sample used was concussion, -1 CFU), Verify critical injury is properly applied to character sheet. Alternately simply add a modifier to a CFU roll.
2. Roll CFU

![crit1](https://user-images.githubusercontent.com/98035055/152651927-e2fb9bcb-9f0e-44ff-8fdd-5b233e017783.PNG)

3. Notice in CFU dialog, Total modifier is 0, yet Concussion is checked.
4. Base die for Roll in example is d10, Modified roll should be d8.
![crit2](https://user-images.githubusercontent.com/98035055/152651935-035cb752-e0f9-4afb-ba34-742c2f5786a4.PNG)

5. Roll.. D10 is produced unmodified.
![crit3](https://user-images.githubusercontent.com/98035055/152651981-567bc2ce-a25b-49c8-b63b-bdc80e594aa0.PNG)

### Expected Behavior
Dice to be modified properly when crits or other modifiers are applied.

### Screenshots
Added during steps.

### Additional Context
This behavior is also present simply applying a modifier to a CFU roll, any modifier will not modify the base roll.
Oddly unchecking the critical actually adds a +1 modifier???? yet it still does not affect the base die.
![crit4](https://user-images.githubusercontent.com/98035055/152652197-811ccb96-b57a-4482-80f6-2e9ea3afecdd.PNG)

**Comment by tinwe** [comment]
Wouldn't the Unit morale be added as well? In this case a D6, which would be modified away by -1 ?

**Comment by AtraAngelis** [comment]
The add unit morale check box is not checked. Thus no D6 should have been added. The roll presented would be a strait CUF roll against an individual. The roll should be a D10 with a -1 crit, thus rolling a D8.

In any case even manually adding a large negative or positive modifier to the roll causes no effect to the skill die. It still rolls a D10 in this case.
