### ISSUE TITLE
Vechicles are missing sidearmor

### ISSUE THREAD

**Issue by Kayne** [Stefouch/t2k4e#82]
### Describe the Bug

After splitting side armor to left and right, now all vechicles has 0 armor set for left and right. It's true for already placed tokens and for new Actors.

### Severity

- Medium (minor functional impact)

**Comment by Stefouch** [comment]
1. Is this true for already created actors ?
2. Is this true for newly created actors ?
3. Is this true for newly created tokens ?

**Comment by Kayne** [comment]
It's true for all already imported actors. However, when I checked the Compendium, there are already fixed values. So removing all items and reimporting them from Compendium would fix armor values.

**Comment by Stefouch** [comment]
I hope the fix resolves the issue for any future migration.
