### ISSUE TITLE
Private rolls not being obfuscated

### ISSUE THREAD

**Issue by tinwe** [Stefouch/t2k4e#92]
### Describe the Bug
I'd like to report a bug however. I don't know if it's a bug in the Foundry core, in Dice so nice, or in the T2k module, but whenever the GM makes a private roll, the dice shows up as "??" but still displays the exact amount of successes in chat below the dice roll, unobfuscated.
Dice so nice also displays "?" on the dice pips for private GM rolls, but still visualizes the correct amount of dice faces on each dice. This is however not as bad, as showing the amount of successes on the roll.

### Severity
- High (a broken feature, major functional impact)

### Context
Whenever the GM needs to hide or fudge rolls, the players will see the successes anyhow and also what dice used for the roll.

### To Reproduce
Click an NPC action and make the roll private. A greyed out chat box appears for the players about the GM making a private roll with the dice roll replaced with "??", but with the correct number of successes listed below for everyone to see.

### Expected Behavior
Chat box and Dice so nice, should neither display successes nor what dice used for private rolls.

### Screenshots
https://ibb.co/phZqLCn
https://ibb.co/z8Rqvqg

**Comment by Stefouch** [comment]
It seems there are 2 issues in this:

1. The number of successes should be "???" in the chat log
2. Private 3D dice should be hidden

**About (1)**
This is probably tied to our custom roll engine. I'll try to find the source of the issue

**About (2)**
I did not achieved to reproduce your screenshot with "?" on 3D dice. On my Foundry, when I perform a private roll, the 3D dice are only displayed to concerned people. They are not displayed to others (tested with Twilight 2000 and D&D 5E with DiceSoNice as the only active module)

**Comment by tinwe** [comment]
> 

I quite like the visualized Dice so nice roll with ? faces however, but it should use the same dice size on every roll, so the player's can't see the skill level of the opponent, if the GM doesn't want to show it.
